version: '3'

services:
  node:
    build: .
    container_name: node
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/app/src
  postgres:
    build: ./src/db
    container_name: db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: password
    #   POSTGRES_DB: db
    #   POSTGRES_DATABASE: db
    #   POSTGRES_PORT: 5432
    #   POSTGRES_HOST: localhost
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:

